apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web01
  template:
    metadata:
      name: nginx
      labels:
        app: web01
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  externalIPs:
    - 192.168.56.80
  ports:
  - port: 8000
    targetPort: 80
    protocol: TCP
  selector:
    app: web01

